import logoStockfish from '../assets/images/engines/stockfish.png'
import logoStockfishBlue from '../assets/images/engines/stockfish_blue.png'
import logoStockfishPurple from '../assets/images/engines/stockfish_purple.png'

// first engine in the list has highest priority for default engine selection
export default [
  {
    name: 'Stockfish 12',
    binary: 'stockfish',
    logo: logoStockfish,
    variants: [
      'chess',
      'antichess',
      'atomic',
      'crazyhouse',
      'horde',
      'kingofthehill',
      'racingkings',
      '3check',
      'giveaway'
    ]
  },
  {
    name: 'Multi-Variant-Stockfish 10',
    binary: 'multi-variant-stockfish',
    logo: logoStockfishBlue,
    variants: [
      'chess',
      'giveaway',
      'atomic',
      'crazyhouse',
      'extinction',
      'grid',
      'horde',
      'kingofthehill',
      'losers',
      'racingkings',
      '3check',
      'twokings',
      'suicide',
      'bughouse',
      'displacedgrid',
      'loop',
      'placement',
      'slippedgrid',
      'twokingssymmetric'
    ]
  },
  {
    name: 'Fairy Stockfish 11.2',
    binary: 'fairy-stockfish',
    logo: logoStockfishPurple,
    variants: [
      '3check',
      '5check',
      'ai-wok',
      'almost',
      'amazon',
      'antichess',
      'armageddon',
      'asean',
      'ataxx',
      'breakthrough',
      'bughouse',
      'cambodian',
      'capablanca',
      'capahouse',
      'caparandom',
      'centaur',
      'chancellor',
      'chess',
      'chessgi',
      'chigorin',
      'clobber',
      'clobber10',
      'codrus',
      'courier',
      'crazyhouse',
      'dobutsu',
      'embassy',
      'euroshogi',
      'extinction',
      'fairy',
      'fischerandom',
      'gardner',
      'giveaway',
      'gorogoro',
      'gothic',
      'grand',
      'hoppelpoppel',
      'horde',
      'janggi',
      'janggicasual',
      'janggimodern',
      'janggitraditional',
      'janus',
      'jesonmor',
      'judkins',
      'karouk',
      'kinglet',
      'kingofthehill',
      'knightmate',
      'koedem',
      'kyotoshogi',
      'loop',
      'losalamos',
      'losers',
      'makpong',
      'makruk',
      'manchu',
      'micro',
      'mini',
      'minishogi',
      'minixiangqi',
      'modern',
      'newzealand',
      'nocastle',
      'normal',
      'placement',
      'pocketknight',
      'racingkings',
      'seirawan',
      'shako',
      'shatar',
      'shatranj',
      'shogi',
      'shouse',
      'sittuyin',
      'suicide',
      'supply',
      'threekings',
      'xiangqi'
    ]
  }
]
